<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Application/SkillHub.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="../SkillHub.Modules.StudentProfile.Domain/SkillHub.Modules.StudentProfile.Domain.csproj" />
  </ItemGroup>

</Project>
