<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SkillHub.Modules.StudentProfile.Application/SkillHub.Modules.StudentProfile.Application.csproj" />
    <ProjectReference Include="../SkillHub.Modules.StudentProfile.Infrastructure/SkillHub.Modules.StudentProfile.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>
</Project>
