<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SkillHub.Modules.Identity.Application/SkillHub.Modules.Identity.Application.csproj" />
    <ProjectReference Include="../SkillHub.Modules.Identity.Infrastructure/SkillHub.Modules.Identity.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
