<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../SkillHub.Modules.Gamification.Application/SkillHub.Modules.Gamification.Application.csproj" />
    <ProjectReference Include="../SkillHub.Modules.Gamification.Domain/SkillHub.Modules.Gamification.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
