<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>
<ItemGroup>
    <ProjectReference Include="../SkillHub.Modules.Courses.Application/SkillHub.Modules.Courses.Application.csproj" />
    <ProjectReference Include="../SkillHub.Modules.Courses.Infrastructure/SkillHub.Modules.Courses.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
