<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../SkillHub.Modules.Reporting.Application/SkillHub.Modules.Reporting.Application.csproj" />
    <ProjectReference Include="../SkillHub.Modules.Reporting.Domain/SkillHub.Modules.Reporting.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
